
name: Heroku Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: "mateusjoaquim@live.com"
          heroku_app_name: "mateus-case-meli-back-end"
          buildpack: "https://github.com/mateusbrazza/case-meli.git"
          db_url: ${{secrets.DB_URL}}
          db_username: ${{secrets.DATABASE_USERNAME}}
          db_password: ${{secrets.DATABASE_PASSWORD}}

